// Copyright 2026- The corba-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package idlc

import (
	"fmt"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

type GenContext struct {
	ModName    string
	Structs    map[string]*StructNode
	Typedefs   map[string]*TypedefNode
	Enums      map[string]*EnumNode
	Unions     map[string]*UnionNode
	Exceptions map[string]*ExceptionNode
}

// GenerateGoCode generates Go source code from a parsed IDL module.
func GenerateGoCode(mod *ModuleNode, pkgName string) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by idlc. DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "package %s\n\n", pkgName)
	sb.WriteString("import (\n")
	sb.WriteString("\t\"encoding/binary\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"github.com/shjtmy/corba-go/orb/cdr\"\n")
	sb.WriteString("\t\"github.com/shjtmy/corba-go/orb/iiop\"\n")
	sb.WriteString(")\n\n")

	ctx := &GenContext{
		ModName:    mod.Name,
		Structs:    make(map[string]*StructNode),
		Typedefs:   make(map[string]*TypedefNode),
		Enums:      make(map[string]*EnumNode),
		Unions:     make(map[string]*UnionNode),
		Exceptions: make(map[string]*ExceptionNode),
	}

	for _, td := range mod.Typedefs {
		ctx.Typedefs[td.Name] = td
	}
	for _, un := range mod.Unions {
		ctx.Unions[un.Name] = un
	}
	for _, ex := range mod.Exceptions {
		ctx.Exceptions[ex.Name] = ex
	}
	for _, st := range mod.Structs {
		ctx.Structs[st.Name] = st
	}
	for _, en := range mod.Enums {
		ctx.Enums[en.Name] = en
	}

	for _, td := range mod.Typedefs {
		generateTypedef(&sb, td, ctx)
	}

	for _, en := range mod.Enums {
		generateEnum(&sb, en, ctx)
	}

	for _, un := range mod.Unions {
		generateUnion(&sb, un, ctx)
	}

	for _, ex := range mod.Exceptions {
		generateException(&sb, ex, ctx)
	}

	for _, st := range mod.Structs {
		generateStruct(&sb, st, ctx)
	}

	for _, iface := range mod.Interfaces {
		generateInterface(&sb, iface, ctx)
		generateClientStub(&sb, iface, ctx)
		generateServerSkeleton(&sb, iface, ctx)
	}

	return sb.String()
}

// Resolve underlying type for typedefs
func resolveBaseType(idlType string, ctx *GenContext) string {
	if td, ok := ctx.Typedefs[idlType]; ok {
		return resolveBaseType(td.Type, ctx)
	}
	return idlType
}

func mapTypeToGo(idlType string, ctx *GenContext) string {
	if strings.HasPrefix(idlType, "sequence<") && strings.HasSuffix(idlType, ">") {
		inner := idlType[9 : len(idlType)-1]
		return "[]" + mapTypeToGo(inner, ctx)
	}

	switch idlType {
	case "short":
		return "int16"
	case "ushort":
		return "uint16"
	case "long":
		return "int32"
	case "ulong":
		return "uint32"
	case "longlong":
		return "int64"
	case "ulonglong":
		return "uint64"
	case "float":
		return "float32"
	case "double":
		return "float64"
	case "boolean":
		return "bool"
	case "string", "Object":
		return "string"
	case "octet":
		return "byte"
	case "any":
		return "cdr.Any"
	default:
		if _, ok := ctx.Structs[idlType]; ok {
			return fmt.Sprintf("*%s_%s", ctx.ModName, idlType)
		}
		if _, ok := ctx.Unions[idlType]; ok {
			return fmt.Sprintf("*%s_%s", ctx.ModName, idlType)
		}
		if _, ok := ctx.Exceptions[idlType]; ok {
			return fmt.Sprintf("*%s_%s", ctx.ModName, idlType)
		}
		if _, ok := ctx.Enums[idlType]; ok {
			return fmt.Sprintf("%s_%s", ctx.ModName, idlType)
		}
		if _, ok := ctx.Typedefs[idlType]; ok {
			return fmt.Sprintf("%s_%s", ctx.ModName, idlType)
		}
		return "interface{}"
	}
}

func generateEncode(sb *strings.Builder, valName string, idlType string, ctx *GenContext, indent string) {
	if strings.HasPrefix(idlType, "sequence<") && strings.HasSuffix(idlType, ">") {
		inner := idlType[9 : len(idlType)-1]
		fmt.Fprintf(sb, "%senc.EncodeULong(uint32(len(%s)))\n", indent, valName)
		fmt.Fprintf(sb, "%sfor _, v := range %s {\n", indent, valName)
		generateEncode(sb, "v", inner, ctx, indent+"\t")
		fmt.Fprintf(sb, "%s}\n", indent)
		return
	}

	baseType := resolveBaseType(idlType, ctx)

	switch baseType {
	case "short":
		if idlType != baseType {
			fmt.Fprintf(sb, "%senc.EncodeShort(int16(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%senc.EncodeShort(%s)\n", indent, valName)
		}
	case "ushort":
		if idlType != baseType {
			fmt.Fprintf(sb, "%senc.EncodeUShort(uint16(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%senc.EncodeUShort(%s)\n", indent, valName)
		}
	case "long":
		if idlType != baseType {
			fmt.Fprintf(sb, "%senc.EncodeLong(int32(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%senc.EncodeLong(%s)\n", indent, valName)
		}
	case "ulong":
		if idlType != baseType {
			fmt.Fprintf(sb, "%senc.EncodeULong(uint32(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%senc.EncodeULong(%s)\n", indent, valName)
		}
	case "float":
		if idlType != baseType {
			fmt.Fprintf(sb, "%senc.EncodeFloat(float32(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%senc.EncodeFloat(%s)\n", indent, valName)
		}
	case "double":
		if idlType != baseType {
			fmt.Fprintf(sb, "%senc.EncodeDouble(float64(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%senc.EncodeDouble(%s)\n", indent, valName)
		}
	case "boolean":
		if idlType != baseType {
			fmt.Fprintf(sb, "%senc.EncodeBoolean(bool(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%senc.EncodeBoolean(%s)\n", indent, valName)
		}
	case "string":
		if idlType != baseType {
			fmt.Fprintf(sb, "%senc.EncodeString(string(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%senc.EncodeString(%s)\n", indent, valName)
		}
	case "octet":
		if idlType != baseType {
			fmt.Fprintf(sb, "%senc.EncodeOctet(byte(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%senc.EncodeOctet(%s)\n", indent, valName)
		}
	case "any":
		fmt.Fprintf(sb, "%senc.EncodeAny(%s)\n", indent, valName)
	default:
		if _, ok := ctx.Structs[baseType]; ok {
			fmt.Fprintf(sb, "%s%s.Encode(enc)\n", indent, valName)
		} else if _, ok := ctx.Unions[baseType]; ok {
			fmt.Fprintf(sb, "%s%s.Encode(enc)\n", indent, valName)
		} else if _, ok := ctx.Exceptions[baseType]; ok {
			fmt.Fprintf(sb, "%s%s.Encode(enc)\n", indent, valName)
		} else if _, ok := ctx.Enums[baseType]; ok {
			// Enums are encoded as ulong
			fmt.Fprintf(sb, "%senc.EncodeULong(uint32(%s))\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%s// FIXME: unhandled encode for %s\n", indent, idlType)
		}
	}
}

func generateDecode(sb *strings.Builder, valName string, idlType string, ctx *GenContext, indent string, declare bool, errDeclare bool) {
	errAssign := "="
	if errDeclare {
		errAssign = ":="
	}

	tmpName := strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(valName, ".", "_"), "[", "_"), "]", "_")

	if strings.HasPrefix(idlType, "sequence<") && strings.HasSuffix(idlType, ">") {
		inner := idlType[9 : len(idlType)-1]
		goType := mapTypeToGo(idlType, ctx)
		fmt.Fprintf(sb, "%s_len_%s, _ := dec.DecodeULong()\n", indent, valName)
		if declare {
			fmt.Fprintf(sb, "%s%s := make(%s, _len_%s)\n", indent, valName, goType, valName)
		} else {
			fmt.Fprintf(sb, "%s%s = make(%s, _len_%s)\n", indent, valName, goType, valName)
		}
		fmt.Fprintf(sb, "%sfor _i_%s := uint32(0); _i_%s < _len_%s; _i_%s++ {\n", indent, valName, valName, valName, valName)
		generateDecode(sb, fmt.Sprintf("%s[_i_%s]", valName, valName), inner, ctx, indent+"\t", false, false)
		fmt.Fprintf(sb, "%s}\n", indent)
		return
	}

	baseType := resolveBaseType(idlType, ctx)
	isCustomType := (idlType != baseType)
	castType := mapTypeToGo(idlType, ctx)

	switch baseType {
	case "short":
		if declare {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeShort()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		} else {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeShort()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		}
	case "ushort":
		if declare {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeUShort()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		} else {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeUShort()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		}
	case "long":
		if declare {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeLong()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		} else {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeLong()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		}
	case "ulong":
		if declare {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeULong()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		} else {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeULong()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		}
	case "float":
		if declare {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeFloat()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		} else {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeFloat()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		}
	case "double":
		if declare {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeDouble()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		} else {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeDouble()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		}
	case "boolean":
		if declare {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeBoolean()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		} else {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeBoolean()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		}
	case "string":
		if declare {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeString()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		} else {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeString()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		}
	case "octet":
		if declare {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeOctet()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		} else {
			fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeOctet()\n", indent, tmpName)
			fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
		}
	case "any":
		if declare {
			fmt.Fprintf(sb, "%s%s, err := dec.DecodeAny()\n", indent, valName)
		} else {
			fmt.Fprintf(sb, "%s%s, err %s dec.DecodeAny()\n", indent, valName, errAssign)
		}
	default:
		if _, ok := ctx.Structs[baseType]; ok {
			if declare {
				fmt.Fprintf(sb, "%s%s := &%s_%s{}\n", indent, valName, ctx.ModName, baseType)
				fmt.Fprintf(sb, "%serr := %s.Decode(dec)\n", indent, valName)
			} else {
				fmt.Fprintf(sb, "%s%s = &%s_%s{}\n", indent, valName, ctx.ModName, baseType)
				fmt.Fprintf(sb, "%serr %s %s.Decode(dec)\n", indent, errAssign, valName)
			}
		} else if _, ok := ctx.Unions[baseType]; ok {
			if declare {
				fmt.Fprintf(sb, "%s%s := &%s_%s{}\n", indent, valName, ctx.ModName, baseType)
				fmt.Fprintf(sb, "%serr := %s.Decode(dec)\n", indent, valName)
			} else {
				fmt.Fprintf(sb, "%s%s = &%s_%s{}\n", indent, valName, ctx.ModName, baseType)
				fmt.Fprintf(sb, "%serr %s %s.Decode(dec)\n", indent, errAssign, valName)
			}
		} else if _, ok := ctx.Exceptions[baseType]; ok {
			if declare {
				fmt.Fprintf(sb, "%s%s := &%s_%s{}\n", indent, valName, ctx.ModName, baseType)
				fmt.Fprintf(sb, "%serr := %s.Decode(dec)\n", indent, valName)
			} else {
				fmt.Fprintf(sb, "%s%s = &%s_%s{}\n", indent, valName, ctx.ModName, baseType)
				fmt.Fprintf(sb, "%serr %s %s.Decode(dec)\n", indent, errAssign, valName)
			}
		} else if _, ok := ctx.Enums[baseType]; ok {
			if declare {
				fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeULong()\n", indent, tmpName)
				fmt.Fprintf(sb, "%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName)
			} else {
				fmt.Fprintf(sb, "%s_tmp_%s, err := dec.DecodeULong()\n", indent, tmpName)
				fmt.Fprintf(sb, "%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName)
			}
		} else {
			fmt.Fprintf(sb, "%s// FIXME: unhandled decode for %s (base: %s)\n", indent, idlType, baseType)
			if declare {
				fmt.Fprintf(sb, "%svar %s %s\n", indent, valName, castType)
			}
		}
	}
	fmt.Fprintf(sb, "%s_ = err\n", indent) // ignore unused error warning
	fmt.Fprintf(sb, "%s_ = dec\n", indent) // ignore unused dec warning
	_ = isCustomType                       // suppress unused
}

func generateTypedef(sb *strings.Builder, td *TypedefNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, td.Name)
	goType := mapTypeToGo(td.Type, ctx)
	fmt.Fprintf(sb, "type %s %s\n\n", name, goType)
}

func generateEnum(sb *strings.Builder, en *EnumNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, en.Name)
	fmt.Fprintf(sb, "type %s uint32\n\n", name)

	sb.WriteString("const (\n")
	for i, val := range en.Values {
		fmt.Fprintf(sb, "\t%s_%s %s = %d\n", name, val, name, i)
	}
	sb.WriteString(")\n\n")
}

func generateUnion(sb *strings.Builder, un *UnionNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, un.Name)
	switchGoType := mapTypeToGo(un.SwitchType, ctx)

	fmt.Fprintf(sb, "type %s struct {\n", name)
	fmt.Fprintf(sb, "\tDiscriminator %s\n", switchGoType)
	for _, c := range un.Cases {
		fName := titleCase(c.Name)
		fmt.Fprintf(sb, "\t%s %s\n", fName, mapTypeToGo(c.Type, ctx))
	}
	sb.WriteString("}\n\n")

	// Encode
	fmt.Fprintf(sb, "func (u *%s) Encode(enc *cdr.Encoder) {\n", name)
	generateEncode(sb, "u.Discriminator", un.SwitchType, ctx, "\t")
	sb.WriteString("\tswitch u.Discriminator {\n")
	for _, c := range un.Cases {
		if c.IsDefault {
			sb.WriteString("\tdefault:\n")
		} else {
			var labelStrs []string
			labelStrs = append(labelStrs, c.Labels...)
			fmt.Fprintf(sb, "\tcase %s:\n", strings.Join(labelStrs, ", "))
		}
		generateEncode(sb, "u."+titleCase(c.Name), c.Type, ctx, "\t\t")
	}
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	// Decode
	fmt.Fprintf(sb, "func (u *%s) Decode(dec *cdr.Decoder) error {\n", name)
	sb.WriteString("\tvar err error\n")
	sb.WriteString("\t_ = dec\n")
	generateDecode(sb, "u.Discriminator", un.SwitchType, ctx, "\t", false, false)
	sb.WriteString("\tif err != nil { return err }\n")
	sb.WriteString("\tswitch u.Discriminator {\n")
	for _, c := range un.Cases {
		if c.IsDefault {
			sb.WriteString("\tdefault:\n")
		} else {
			var labelStrs []string
			labelStrs = append(labelStrs, c.Labels...)
			fmt.Fprintf(sb, "\tcase %s:\n", strings.Join(labelStrs, ", "))
		}
		generateDecode(sb, "u."+titleCase(c.Name), c.Type, ctx, "\t\t", false, false)
		sb.WriteString("\t\tif err != nil { return err }\n")
	}
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")
}

func generateException(sb *strings.Builder, ex *ExceptionNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, ex.Name)
	fmt.Fprintf(sb, "type %s struct {\n", name)
	for _, f := range ex.Fields {
		fmt.Fprintf(sb, "\t%s %s\n", titleCase(f.Name), mapTypeToGo(f.Type, ctx))
	}
	sb.WriteString("}\n\n")

	fmt.Fprintf(sb, "func (e *%s) Error() string {\n", name)
	fmt.Fprintf(sb, "\treturn \"%s\"\n", name)
	sb.WriteString("}\n\n")

	// Encode method
	fmt.Fprintf(sb, "func (s *%s) Encode(enc *cdr.Encoder) {\n", name)
	for _, f := range ex.Fields {
		generateEncode(sb, "s."+titleCase(f.Name), f.Type, ctx, "\t")
	}
	sb.WriteString("}\n\n")

	// Decode method
	fmt.Fprintf(sb, "func (s *%s) Decode(dec *cdr.Decoder) error {\n", name)
	sb.WriteString("\tvar err error\n")
	sb.WriteString("\t_ = err\n")
	sb.WriteString("\t_ = dec\n")
	for _, f := range ex.Fields {
		generateDecode(sb, "s."+titleCase(f.Name), f.Type, ctx, "\t", false, false)
		sb.WriteString("\tif err != nil { return err }\n")
	}
	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")
}

func generateStruct(sb *strings.Builder, st *StructNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, st.Name)
	fmt.Fprintf(sb, "type %s struct {\n", name)
	for _, f := range st.Fields {
		fmt.Fprintf(sb, "\t%s %s\n", titleCase(f.Name), mapTypeToGo(f.Type, ctx))
	}
	sb.WriteString("}\n\n")

	// Encode method
	fmt.Fprintf(sb, "func (s *%s) Encode(enc *cdr.Encoder) {\n", name)
	for _, f := range st.Fields {
		generateEncode(sb, "s."+titleCase(f.Name), f.Type, ctx, "\t")
	}
	sb.WriteString("}\n\n")

	// Decode method
	fmt.Fprintf(sb, "func (s *%s) Decode(dec *cdr.Decoder) error {\n", name)
	sb.WriteString("\tvar err error\n")
	sb.WriteString("\t_ = err\n")
	sb.WriteString("\t_ = dec\n")
	for _, f := range st.Fields {
		generateDecode(sb, "s."+titleCase(f.Name), f.Type, ctx, "\t", false, false)
		sb.WriteString("\tif err != nil { return err }\n")
	}
	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")
}

func generateInterface(sb *strings.Builder, iface *InterfaceNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, iface.Name)
	fmt.Fprintf(sb, "type %s interface {\n", name)

	for _, op := range iface.Operations {
		retTypeStr := ""
		if op.ReturnType != "void" && op.ReturnType != "" {
			retTypeStr = mapTypeToGo(op.ReturnType, ctx) + ", "
		}

		var params []string
		for _, p := range op.Parameters {
			params = append(params, fmt.Sprintf("%s %s", p.Name, mapTypeToGo(p.Type, ctx)))
		}

		fmt.Fprintf(sb, "\t%s(%s) (%serror)\n", titleCase(op.Name), strings.Join(params, ", "), retTypeStr)
	}
	sb.WriteString("}\n\n")
}

func generateClientStub(sb *strings.Builder, iface *InterfaceNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s_Stub", ctx.ModName, iface.Name)
	ifaceName := fmt.Sprintf("%s_%s", ctx.ModName, iface.Name)

	fmt.Fprintf(sb, "type %s struct {\n", name)
	sb.WriteString("\tclient *iiop.Client\n")
	sb.WriteString("\tobjectKey []byte\n")
	sb.WriteString("}\n\n")

	fmt.Fprintf(sb, "func New%s(client *iiop.Client, objectKey []byte) %s {\n", name, ifaceName)
	fmt.Fprintf(sb, "\treturn &%s{client: client, objectKey: objectKey}\n", name)
	sb.WriteString("}\n\n")

	for _, op := range iface.Operations {
		var params []string
		for _, p := range op.Parameters {
			params = append(params, fmt.Sprintf("%s %s", p.Name, mapTypeToGo(p.Type, ctx)))
		}

		retTypeStr := ""
		if op.ReturnType != "void" && op.ReturnType != "" {
			retTypeStr = mapTypeToGo(op.ReturnType, ctx) + ", "
		}

		fmt.Fprintf(sb, "func (s *%s) %s(%s) (%serror) {\n", name, titleCase(op.Name), strings.Join(params, ", "), retTypeStr)

		sb.WriteString("\tenc := cdr.NewEncoder(binary.LittleEndian)\n")
		for _, p := range op.Parameters {
			generateEncode(sb, p.Name, p.Type, ctx, "\t")
		}

		fmt.Fprintf(sb, "\treply, err := s.client.Invoke(s.objectKey, \"%s\", enc.Bytes())\n", op.Name)
		if op.ReturnType != "void" && op.ReturnType != "" {
			goRetType := mapTypeToGo(op.ReturnType, ctx)
			sb.WriteString("\tif err != nil {\n")
			fmt.Fprintf(sb, "\t\tvar zero %s\n", goRetType)
			sb.WriteString("\t\treturn zero, err\n")
			sb.WriteString("\t}\n\n")

			sb.WriteString("\tdec := cdr.NewDecoder(reply, binary.LittleEndian)\n")
			sb.WriteString("\t_ = dec\n")
			generateDecode(sb, "ret", op.ReturnType, ctx, "\t", true, true)
			sb.WriteString("\treturn ret, err\n")
		} else {
			sb.WriteString("\tif err != nil {\n")
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n\n")

			sb.WriteString("\tdec := cdr.NewDecoder(reply, binary.LittleEndian)\n")
			sb.WriteString("\t_ = dec\n")
			sb.WriteString("\treturn nil\n")
		}

		sb.WriteString("}\n\n")
	}
}

func generateServerSkeleton(sb *strings.Builder, iface *InterfaceNode, ctx *GenContext) {
	ifaceName := fmt.Sprintf("%s_%s", ctx.ModName, iface.Name)

	fmt.Fprintf(sb, "func %s_Skeleton(impl %s) iiop.Handler {\n", ifaceName, ifaceName)
	sb.WriteString("\treturn func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {\n")
	sb.WriteString("\t\tdec := cdr.NewDecoder(reqPayload, binary.LittleEndian)\n")
	sb.WriteString("\t\tvar err error\n")
	sb.WriteString("\t\t_ = err\n")
	sb.WriteString("\t\t_ = dec\n")
	sb.WriteString("\t\tswitch operation {\n")

	for _, op := range iface.Operations {
		fmt.Fprintf(sb, "\t\tcase \"%s\":\n", op.Name)

		var callArgs []string
		for _, p := range op.Parameters {
			generateDecode(sb, "arg_"+p.Name, p.Type, ctx, "\t\t\t", true, false)
			callArgs = append(callArgs, "arg_"+p.Name)
		}

		if op.ReturnType != "void" && op.ReturnType != "" {
			fmt.Fprintf(sb, "\t\t\tret, err := impl.%s(%s)\n", titleCase(op.Name), strings.Join(callArgs, ", "))
			sb.WriteString("\t\t\t_ = ret\n")
			sb.WriteString("\t\t\tif err != nil {\n")
			sb.WriteString("\t\t\t\treturn nil, err\n")
			sb.WriteString("\t\t\t}\n")
			sb.WriteString("\t\t\tenc := cdr.NewEncoder(binary.LittleEndian)\n")
			generateEncode(sb, "ret", op.ReturnType, ctx, "\t\t\t")
			sb.WriteString("\t\t\treturn enc.Bytes(), nil\n")
		} else {
			fmt.Fprintf(sb, "\t\t\terr = impl.%s(%s)\n", titleCase(op.Name), strings.Join(callArgs, ", "))
			sb.WriteString("\t\t\tif err != nil {\n")
			sb.WriteString("\t\t\t\treturn nil, err\n")
			sb.WriteString("\t\t\t}\n")
			sb.WriteString("\t\t\tenc := cdr.NewEncoder(binary.LittleEndian)\n")
			sb.WriteString("\t\t\treturn enc.Bytes(), nil\n")
		}
	}

	sb.WriteString("\t\tdefault:\n")
	sb.WriteString("\t\t\treturn nil, fmt.Errorf(\"Unknown operation: %s\", operation)\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")
}

// titleCase converts the first letter of a string to upper case.
func titleCase(s string) string {
	return cases.Title(language.Und, cases.NoLower).String(s)
}
