package idlc

import (
	"fmt"
	"strings"
)

type GenContext struct {
	ModName    string
	Structs    map[string]*StructNode
	Typedefs   map[string]*TypedefNode
	Enums      map[string]*EnumNode
	Unions     map[string]*UnionNode
	Exceptions map[string]*ExceptionNode
}

// GenerateGoCode generates Go source code from a parsed IDL module.
func GenerateGoCode(mod *ModuleNode, pkgName string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("// Code generated by idlc. DO NOT EDIT.\n"))
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	sb.WriteString("import (\n")
	sb.WriteString("\t\"encoding/binary\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"github.com/shjtmy/corba-go/orb/cdr\"\n")
	sb.WriteString("\t\"github.com/shjtmy/corba-go/orb/iiop\"\n")
	sb.WriteString(")\n\n")

	ctx := &GenContext{
		ModName:    mod.Name,
		Structs:    make(map[string]*StructNode),
		Typedefs:   make(map[string]*TypedefNode),
		Enums:      make(map[string]*EnumNode),
		Unions:     make(map[string]*UnionNode),
		Exceptions: make(map[string]*ExceptionNode),
	}

	for _, td := range mod.Typedefs {
		ctx.Typedefs[td.Name] = td
	}
	for _, un := range mod.Unions {
		ctx.Unions[un.Name] = un
	}
	for _, ex := range mod.Exceptions {
		ctx.Exceptions[ex.Name] = ex
	}
	for _, st := range mod.Structs {
		ctx.Structs[st.Name] = st
	}
	for _, en := range mod.Enums {
		ctx.Enums[en.Name] = en
	}

	for _, td := range mod.Typedefs {
		generateTypedef(&sb, td, ctx)
	}

	for _, en := range mod.Enums {
		generateEnum(&sb, en, ctx)
	}

	for _, un := range mod.Unions {
		generateUnion(&sb, un, ctx)
	}

	for _, ex := range mod.Exceptions {
		generateException(&sb, ex, ctx)
	}

	for _, st := range mod.Structs {
		generateStruct(&sb, st, ctx)
	}

	for _, iface := range mod.Interfaces {
		generateInterface(&sb, iface, ctx)
		generateClientStub(&sb, iface, ctx)
		generateServerSkeleton(&sb, iface, ctx)
	}

	return sb.String()
}

// Resolve underlying type for typedefs
func resolveBaseType(idlType string, ctx *GenContext) string {
	if td, ok := ctx.Typedefs[idlType]; ok {
		return resolveBaseType(td.Type, ctx)
	}
	return idlType
}

func mapTypeToGo(idlType string, ctx *GenContext) string {
	if strings.HasPrefix(idlType, "sequence<") && strings.HasSuffix(idlType, ">") {
		inner := idlType[9 : len(idlType)-1]
		return "[]" + mapTypeToGo(inner, ctx)
	}

	switch idlType {
	case "short":
		return "int16"
	case "ushort":
		return "uint16"
	case "long":
		return "int32"
	case "ulong":
		return "uint32"
	case "longlong":
		return "int64"
	case "ulonglong":
		return "uint64"
	case "float":
		return "float32"
	case "double":
		return "float64"
	case "boolean":
		return "bool"
	case "string", "Object":
		return "string"
	case "octet":
		return "byte"
	case "any":
		return "cdr.Any"
	default:
		if _, ok := ctx.Structs[idlType]; ok {
			return fmt.Sprintf("*%s_%s", ctx.ModName, idlType)
		}
		if _, ok := ctx.Unions[idlType]; ok {
			return fmt.Sprintf("*%s_%s", ctx.ModName, idlType)
		}
		if _, ok := ctx.Exceptions[idlType]; ok {
			return fmt.Sprintf("*%s_%s", ctx.ModName, idlType)
		}
		if _, ok := ctx.Enums[idlType]; ok {
			return fmt.Sprintf("%s_%s", ctx.ModName, idlType)
		}
		if _, ok := ctx.Typedefs[idlType]; ok {
			return fmt.Sprintf("%s_%s", ctx.ModName, idlType)
		}
		return "interface{}"
	}
}

func generateEncode(sb *strings.Builder, valName string, idlType string, ctx *GenContext, indent string) {
	if strings.HasPrefix(idlType, "sequence<") && strings.HasSuffix(idlType, ">") {
		inner := idlType[9 : len(idlType)-1]
		sb.WriteString(fmt.Sprintf("%senc.EncodeULong(uint32(len(%s)))\n", indent, valName))
		sb.WriteString(fmt.Sprintf("%sfor _, v := range %s {\n", indent, valName))
		generateEncode(sb, "v", inner, ctx, indent+"\t")
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
		return
	}

	baseType := resolveBaseType(idlType, ctx)

	switch baseType {
	case "short":
		if idlType != baseType {
			sb.WriteString(fmt.Sprintf("%senc.EncodeShort(int16(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%senc.EncodeShort(%s)\n", indent, valName))
		}
	case "ushort":
		if idlType != baseType {
			sb.WriteString(fmt.Sprintf("%senc.EncodeUShort(uint16(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%senc.EncodeUShort(%s)\n", indent, valName))
		}
	case "long":
		if idlType != baseType {
			sb.WriteString(fmt.Sprintf("%senc.EncodeLong(int32(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%senc.EncodeLong(%s)\n", indent, valName))
		}
	case "ulong":
		if idlType != baseType {
			sb.WriteString(fmt.Sprintf("%senc.EncodeULong(uint32(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%senc.EncodeULong(%s)\n", indent, valName))
		}
	case "float":
		if idlType != baseType {
			sb.WriteString(fmt.Sprintf("%senc.EncodeFloat(float32(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%senc.EncodeFloat(%s)\n", indent, valName))
		}
	case "double":
		if idlType != baseType {
			sb.WriteString(fmt.Sprintf("%senc.EncodeDouble(float64(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%senc.EncodeDouble(%s)\n", indent, valName))
		}
	case "boolean":
		if idlType != baseType {
			sb.WriteString(fmt.Sprintf("%senc.EncodeBoolean(bool(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%senc.EncodeBoolean(%s)\n", indent, valName))
		}
	case "string":
		if idlType != baseType {
			sb.WriteString(fmt.Sprintf("%senc.EncodeString(string(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%senc.EncodeString(%s)\n", indent, valName))
		}
	case "octet":
		if idlType != baseType {
			sb.WriteString(fmt.Sprintf("%senc.EncodeOctet(byte(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%senc.EncodeOctet(%s)\n", indent, valName))
		}
	case "any":
		sb.WriteString(fmt.Sprintf("%senc.EncodeAny(%s)\n", indent, valName))
	default:
		if _, ok := ctx.Structs[baseType]; ok {
			sb.WriteString(fmt.Sprintf("%s%s.Encode(enc)\n", indent, valName))
		} else if _, ok := ctx.Unions[baseType]; ok {
			sb.WriteString(fmt.Sprintf("%s%s.Encode(enc)\n", indent, valName))
		} else if _, ok := ctx.Exceptions[baseType]; ok {
			sb.WriteString(fmt.Sprintf("%s%s.Encode(enc)\n", indent, valName))
		} else if _, ok := ctx.Enums[baseType]; ok {
			// Enums are encoded as ulong
			sb.WriteString(fmt.Sprintf("%senc.EncodeULong(uint32(%s))\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%s// FIXME: unhandled encode for %s\n", indent, idlType))
		}
	}
}

func generateDecode(sb *strings.Builder, valName string, idlType string, ctx *GenContext, indent string, declare bool, errDeclare bool) {
	errAssign := "="
	if errDeclare {
		errAssign = ":="
	}

	tmpName := strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(valName, ".", "_"), "[", "_"), "]", "_")

	if strings.HasPrefix(idlType, "sequence<") && strings.HasSuffix(idlType, ">") {
		inner := idlType[9 : len(idlType)-1]
		goType := mapTypeToGo(idlType, ctx)
		sb.WriteString(fmt.Sprintf("%s_len_%s, _ := dec.DecodeULong()\n", indent, valName))
		if declare {
			sb.WriteString(fmt.Sprintf("%s%s := make(%s, _len_%s)\n", indent, valName, goType, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%s%s = make(%s, _len_%s)\n", indent, valName, goType, valName))
		}
		sb.WriteString(fmt.Sprintf("%sfor _i_%s := uint32(0); _i_%s < _len_%s; _i_%s++ {\n", indent, valName, valName, valName, valName))
		generateDecode(sb, fmt.Sprintf("%s[_i_%s]", valName, valName), inner, ctx, indent+"\t", false, false)
		sb.WriteString(fmt.Sprintf("%s}\n", indent))
		return
	}

	baseType := resolveBaseType(idlType, ctx)
	isCustomType := (idlType != baseType)
	castType := mapTypeToGo(idlType, ctx)

	switch baseType {
	case "short":
		if declare {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeShort()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		} else {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeShort()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		}
	case "ushort":
		if declare {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeUShort()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		} else {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeUShort()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		}
	case "long":
		if declare {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeLong()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		} else {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeLong()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		}
	case "ulong":
		if declare {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeULong()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		} else {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeULong()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		}
	case "float":
		if declare {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeFloat()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		} else {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeFloat()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		}
	case "double":
		if declare {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeDouble()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		} else {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeDouble()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		}
	case "boolean":
		if declare {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeBoolean()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		} else {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeBoolean()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		}
	case "string":
		if declare {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeString()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		} else {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeString()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		}
	case "octet":
		if declare {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeOctet()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		} else {
			sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeOctet()\n", indent, tmpName))
			sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
		}
	case "any":
		if declare {
			sb.WriteString(fmt.Sprintf("%s%s, err := dec.DecodeAny()\n", indent, valName))
		} else {
			sb.WriteString(fmt.Sprintf("%s%s, err %s dec.DecodeAny()\n", indent, valName, errAssign))
		}
	default:
		if _, ok := ctx.Structs[baseType]; ok {
			if declare {
				sb.WriteString(fmt.Sprintf("%s%s := &%s_%s{}\n", indent, valName, ctx.ModName, baseType))
				sb.WriteString(fmt.Sprintf("%serr := %s.Decode(dec)\n", indent, valName))
			} else {
				sb.WriteString(fmt.Sprintf("%s%s = &%s_%s{}\n", indent, valName, ctx.ModName, baseType))
				sb.WriteString(fmt.Sprintf("%serr %s %s.Decode(dec)\n", indent, valName, errAssign, valName))
			}
		} else if _, ok := ctx.Unions[baseType]; ok {
			if declare {
				sb.WriteString(fmt.Sprintf("%s%s := &%s_%s{}\n", indent, valName, ctx.ModName, baseType))
				sb.WriteString(fmt.Sprintf("%serr := %s.Decode(dec)\n", indent, valName))
			} else {
				sb.WriteString(fmt.Sprintf("%s%s = &%s_%s{}\n", indent, valName, ctx.ModName, baseType))
				sb.WriteString(fmt.Sprintf("%serr %s %s.Decode(dec)\n", indent, valName, errAssign, valName))
			}
		} else if _, ok := ctx.Exceptions[baseType]; ok {
			if declare {
				sb.WriteString(fmt.Sprintf("%s%s := &%s_%s{}\n", indent, valName, ctx.ModName, baseType))
				sb.WriteString(fmt.Sprintf("%serr := %s.Decode(dec)\n", indent, valName))
			} else {
				sb.WriteString(fmt.Sprintf("%s%s = &%s_%s{}\n", indent, valName, ctx.ModName, baseType))
				sb.WriteString(fmt.Sprintf("%serr %s %s.Decode(dec)\n", indent, valName, errAssign, valName))
			}
		} else if _, ok := ctx.Enums[baseType]; ok {
			if declare {
				sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeULong()\n", indent, tmpName))
				sb.WriteString(fmt.Sprintf("%s%s := %s(_tmp_%s)\n", indent, valName, castType, tmpName))
			} else {
				sb.WriteString(fmt.Sprintf("%s_tmp_%s, err := dec.DecodeULong()\n", indent, tmpName))
				sb.WriteString(fmt.Sprintf("%s%s = %s(_tmp_%s)\n", indent, valName, castType, tmpName))
			}
		} else {
			sb.WriteString(fmt.Sprintf("%s// FIXME: unhandled decode for %s (base: %s)\n", indent, idlType, baseType))
			if declare {
				sb.WriteString(fmt.Sprintf("%svar %s %s\n", indent, valName, castType))
			}
		}
	}
	sb.WriteString(fmt.Sprintf("%s_ = err\n", indent)) // ignore unused error warning
	sb.WriteString(fmt.Sprintf("%s_ = dec\n", indent)) // ignore unused dec warning
	_ = isCustomType                                   // suppress unused
}

func generateTypedef(sb *strings.Builder, td *TypedefNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, td.Name)
	goType := mapTypeToGo(td.Type, ctx)
	sb.WriteString(fmt.Sprintf("type %s %s\n\n", name, goType))
}

func generateEnum(sb *strings.Builder, en *EnumNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, en.Name)
	sb.WriteString(fmt.Sprintf("type %s uint32\n\n", name))

	sb.WriteString("const (\n")
	for i, val := range en.Values {
		sb.WriteString(fmt.Sprintf("\t%s_%s %s = %d\n", name, val, name, i))
	}
	sb.WriteString(")\n\n")
}

func generateUnion(sb *strings.Builder, un *UnionNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, un.Name)
	switchGoType := mapTypeToGo(un.SwitchType, ctx)

	sb.WriteString(fmt.Sprintf("type %s struct {\n", name))
	sb.WriteString(fmt.Sprintf("\tDiscriminator %s\n", switchGoType))
	for _, c := range un.Cases {
		fName := strings.Title(c.Name)
		sb.WriteString(fmt.Sprintf("\t%s %s\n", fName, mapTypeToGo(c.Type, ctx)))
	}
	sb.WriteString("}\n\n")

	// Encode
	sb.WriteString(fmt.Sprintf("func (u *%s) Encode(enc *cdr.Encoder) {\n", name))
	generateEncode(sb, "u.Discriminator", un.SwitchType, ctx, "\t")
	sb.WriteString("\tswitch u.Discriminator {\n")
	for _, c := range un.Cases {
		if c.IsDefault {
			sb.WriteString("\tdefault:\n")
		} else {
			var labelStrs []string
			for _, l := range c.Labels {
				labelStrs = append(labelStrs, l)
			}
			sb.WriteString(fmt.Sprintf("\tcase %s:\n", strings.Join(labelStrs, ", ")))
		}
		generateEncode(sb, "u."+strings.Title(c.Name), c.Type, ctx, "\t\t")
	}
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	// Decode
	sb.WriteString(fmt.Sprintf("func (u *%s) Decode(dec *cdr.Decoder) error {\n", name))
	sb.WriteString("\tvar err error\n")
	sb.WriteString("\t_ = dec\n")
	generateDecode(sb, "u.Discriminator", un.SwitchType, ctx, "\t", false, false)
	sb.WriteString("\tif err != nil { return err }\n")
	sb.WriteString("\tswitch u.Discriminator {\n")
	for _, c := range un.Cases {
		if c.IsDefault {
			sb.WriteString("\tdefault:\n")
		} else {
			var labelStrs []string
			for _, l := range c.Labels {
				labelStrs = append(labelStrs, l)
			}
			sb.WriteString(fmt.Sprintf("\tcase %s:\n", strings.Join(labelStrs, ", ")))
		}
		generateDecode(sb, "u."+strings.Title(c.Name), c.Type, ctx, "\t\t", false, false)
		sb.WriteString("\t\tif err != nil { return err }\n")
	}
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")
}

func generateException(sb *strings.Builder, ex *ExceptionNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, ex.Name)
	sb.WriteString(fmt.Sprintf("type %s struct {\n", name))
	for _, f := range ex.Fields {
		sb.WriteString(fmt.Sprintf("\t%s %s\n", strings.Title(f.Name), mapTypeToGo(f.Type, ctx)))
	}
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("func (e *%s) Error() string {\n", name))
	sb.WriteString(fmt.Sprintf("\treturn \"%s\"\n", name))
	sb.WriteString("}\n\n")

	// Encode method
	sb.WriteString(fmt.Sprintf("func (s *%s) Encode(enc *cdr.Encoder) {\n", name))
	for _, f := range ex.Fields {
		generateEncode(sb, "s."+strings.Title(f.Name), f.Type, ctx, "\t")
	}
	sb.WriteString("}\n\n")

	// Decode method
	sb.WriteString(fmt.Sprintf("func (s *%s) Decode(dec *cdr.Decoder) error {\n", name))
	sb.WriteString("\tvar err error\n")
	sb.WriteString("\t_ = err\n")
	sb.WriteString("\t_ = dec\n")
	for _, f := range ex.Fields {
		generateDecode(sb, "s."+strings.Title(f.Name), f.Type, ctx, "\t", false, false)
		sb.WriteString("\tif err != nil { return err }\n")
	}
	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")
}

func generateStruct(sb *strings.Builder, st *StructNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, st.Name)
	sb.WriteString(fmt.Sprintf("type %s struct {\n", name))
	for _, f := range st.Fields {
		sb.WriteString(fmt.Sprintf("\t%s %s\n", strings.Title(f.Name), mapTypeToGo(f.Type, ctx)))
	}
	sb.WriteString("}\n\n")

	// Encode method
	sb.WriteString(fmt.Sprintf("func (s *%s) Encode(enc *cdr.Encoder) {\n", name))
	for _, f := range st.Fields {
		generateEncode(sb, "s."+strings.Title(f.Name), f.Type, ctx, "\t")
	}
	sb.WriteString("}\n\n")

	// Decode method
	sb.WriteString(fmt.Sprintf("func (s *%s) Decode(dec *cdr.Decoder) error {\n", name))
	sb.WriteString("\tvar err error\n")
	sb.WriteString("\t_ = err\n")
	sb.WriteString("\t_ = dec\n")
	for _, f := range st.Fields {
		generateDecode(sb, "s."+strings.Title(f.Name), f.Type, ctx, "\t", false, false)
		sb.WriteString("\tif err != nil { return err }\n")
	}
	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")
}

func generateInterface(sb *strings.Builder, iface *InterfaceNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s", ctx.ModName, iface.Name)
	sb.WriteString(fmt.Sprintf("type %s interface {\n", name))

	for _, op := range iface.Operations {
		retTypeStr := ""
		if op.ReturnType != "void" && op.ReturnType != "" {
			retTypeStr = mapTypeToGo(op.ReturnType, ctx) + ", "
		}

		var params []string
		for _, p := range op.Parameters {
			params = append(params, fmt.Sprintf("%s %s", p.Name, mapTypeToGo(p.Type, ctx)))
		}

		sb.WriteString(fmt.Sprintf("\t%s(%s) (%serror)\n", strings.Title(op.Name), strings.Join(params, ", "), retTypeStr))
	}
	sb.WriteString("}\n\n")
}

func generateClientStub(sb *strings.Builder, iface *InterfaceNode, ctx *GenContext) {
	name := fmt.Sprintf("%s_%s_Stub", ctx.ModName, iface.Name)
	ifaceName := fmt.Sprintf("%s_%s", ctx.ModName, iface.Name)

	sb.WriteString(fmt.Sprintf("type %s struct {\n", name))
	sb.WriteString("\tclient *iiop.Client\n")
	sb.WriteString("\tobjectKey []byte\n")
	sb.WriteString("}\n\n")

	sb.WriteString(fmt.Sprintf("func New%s(client *iiop.Client, objectKey []byte) %s {\n", name, ifaceName))
	sb.WriteString(fmt.Sprintf("\treturn &%s{client: client, objectKey: objectKey}\n", name))
	sb.WriteString("}\n\n")

	for _, op := range iface.Operations {

		var params []string
		for _, p := range op.Parameters {
			params = append(params, fmt.Sprintf("%s %s", p.Name, mapTypeToGo(p.Type, ctx)))
		}

		retTypeStr := ""
		if op.ReturnType != "void" && op.ReturnType != "" {
			retTypeStr = mapTypeToGo(op.ReturnType, ctx) + ", "
		}

		sb.WriteString(fmt.Sprintf("func (s *%s) %s(%s) (%serror) {\n", name, strings.Title(op.Name), strings.Join(params, ", "), retTypeStr))

		sb.WriteString("\tenc := cdr.NewEncoder(binary.LittleEndian)\n")
		for _, p := range op.Parameters {
			generateEncode(sb, p.Name, p.Type, ctx, "\t")
		}

		sb.WriteString(fmt.Sprintf("\treply, err := s.client.Invoke(s.objectKey, \"%s\", enc.Bytes())\n", op.Name))
		if op.ReturnType != "void" && op.ReturnType != "" {
			goRetType := mapTypeToGo(op.ReturnType, ctx)
			sb.WriteString("\tif err != nil {\n")
			sb.WriteString(fmt.Sprintf("\t\tvar zero %s\n", goRetType))
			sb.WriteString("\t\treturn zero, err\n")
			sb.WriteString("\t}\n\n")

			sb.WriteString("\tdec := cdr.NewDecoder(reply, binary.LittleEndian)\n")
			sb.WriteString("\t_ = dec\n")
			generateDecode(sb, "ret", op.ReturnType, ctx, "\t", true, true)
			sb.WriteString("\treturn ret, err\n")
		} else {
			sb.WriteString("\tif err != nil {\n")
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n\n")

			sb.WriteString("\tdec := cdr.NewDecoder(reply, binary.LittleEndian)\n")
			sb.WriteString("\t_ = dec\n")
			sb.WriteString("\treturn nil\n")
		}

		sb.WriteString("}\n\n")
	}
}

func generateServerSkeleton(sb *strings.Builder, iface *InterfaceNode, ctx *GenContext) {
	ifaceName := fmt.Sprintf("%s_%s", ctx.ModName, iface.Name)

	sb.WriteString(fmt.Sprintf("func %s_Skeleton(impl %s) iiop.Handler {\n", ifaceName, ifaceName))
	sb.WriteString("\treturn func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {\n")
	sb.WriteString("\t\tdec := cdr.NewDecoder(reqPayload, binary.LittleEndian)\n")
	sb.WriteString("\t\tvar err error\n")
	sb.WriteString("\t\t_ = err\n")
	sb.WriteString("\t\t_ = dec\n")
	sb.WriteString("\t\tswitch operation {\n")

	for _, op := range iface.Operations {
		sb.WriteString(fmt.Sprintf("\t\tcase \"%s\":\n", op.Name))

		var callArgs []string
		for _, p := range op.Parameters {
			generateDecode(sb, "arg_"+p.Name, p.Type, ctx, "\t\t\t", true, false)
			callArgs = append(callArgs, "arg_"+p.Name)
		}

		if op.ReturnType != "void" && op.ReturnType != "" {
			sb.WriteString(fmt.Sprintf("\t\t\tret, err := impl.%s(%s)\n", strings.Title(op.Name), strings.Join(callArgs, ", ")))
			sb.WriteString("\t\t\t_ = ret\n")
			sb.WriteString("\t\t\tif err != nil {\n")
			sb.WriteString("\t\t\t\treturn nil, err\n")
			sb.WriteString("\t\t\t}\n")
			sb.WriteString("\t\t\tenc := cdr.NewEncoder(binary.LittleEndian)\n")
			generateEncode(sb, "ret", op.ReturnType, ctx, "\t\t\t")
			sb.WriteString("\t\t\treturn enc.Bytes(), nil\n")
		} else {
			sb.WriteString(fmt.Sprintf("\t\t\terr = impl.%s(%s)\n", strings.Title(op.Name), strings.Join(callArgs, ", ")))
			sb.WriteString("\t\t\tif err != nil {\n")
			sb.WriteString("\t\t\t\treturn nil, err\n")
			sb.WriteString("\t\t\t}\n")
			sb.WriteString("\t\t\tenc := cdr.NewEncoder(binary.LittleEndian)\n")
			sb.WriteString("\t\t\treturn enc.Bytes(), nil\n")
		}
	}

	sb.WriteString("\t\tdefault:\n")
	sb.WriteString("\t\t\treturn nil, fmt.Errorf(\"Unknown operation: %s\", operation)\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")
}
