// Copyright 2026- The corba-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by idlc. DO NOT EDIT.
package main

import (
	"encoding/binary"

	"github.com/sh0jitmy/corba-go/orb/cdr"
	"github.com/sh0jitmy/corba-go/orb/iiop"
)

type Calculator_Math_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCalculator_Math_Stub(client *iiop.Client, objectKey []byte) Calculator_Math {
	return &Calculator_Math_Stub{client: client, objectKey: objectKey}
}

func (s *Calculator_Math_Stub) Add(a int32, b int32) (int32, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeLong(a)
	enc.EncodeLong(b)
	reply, err := s.client.Invoke(s.objectKey, "Add", enc.Bytes())
	if err != nil {
		var zero int32
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeLong()
	ret := int32(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

func (s *Calculator_Math_Stub) Echo(msg string) (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeString(msg)
	reply, err := s.client.Invoke(s.objectKey, "Echo", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeString()
	ret := string(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}
