// Code generated by idlc. DO NOT EDIT.
package main

import (
	"encoding/binary"
	"github.com/sh0jitmy/corba-go/orb/cdr"
	"github.com/sh0jitmy/corba-go/orb/iiop"
)

type Calculator_Math_Stub struct {
	client *iiop.Client
	objectKey []byte
}

func NewCalculator_Math_Stub(client *iiop.Client, objectKey []byte) Calculator_Math {
	return &Calculator_Math_Stub{client: client, objectKey: objectKey}
}

func (s *Calculator_Math_Stub) Add(a int32, b int32) (int32, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeLong(a)
	enc.EncodeLong(b)
	reply, err := s.client.Invoke(s.objectKey, "Add", enc.Bytes())
	if err != nil {
		var zero int32
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeLong()
	ret := int32(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

func (s *Calculator_Math_Stub) Echo(msg string) (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeString(msg)
	reply, err := s.client.Invoke(s.objectKey, "Echo", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeString()
	ret := string(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

