// Code generated by idlc. DO NOT EDIT.
package main

import (
	"encoding/binary"
	"fmt"

	"github.com/shjtmy/corba-go/orb/cdr"
	"github.com/shjtmy/corba-go/orb/iiop"
)

type Calculator_Math interface {
	Add(a int32, b int32) (int32, error)
	Echo(msg string) (string, error)
}

type Calculator_Math_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCalculator_Math_Stub(client *iiop.Client, objectKey []byte) Calculator_Math {
	return &Calculator_Math_Stub{client: client, objectKey: objectKey}
}

func (s *Calculator_Math_Stub) Add(a int32, b int32) (int32, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeLong(a)
	enc.EncodeLong(b)
	reply, err := s.client.Invoke(s.objectKey, "Add", enc.Bytes())
	if err != nil {
		var zero int32
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	ret, err := dec.DecodeLong()
	return ret, err
}

func (s *Calculator_Math_Stub) Echo(msg string) (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeString(msg)
	reply, err := s.client.Invoke(s.objectKey, "Echo", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	ret, err := dec.DecodeString()
	return ret, err
}

func Calculator_Math_Skeleton(impl Calculator_Math) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		switch operation {
		case "Add":
			arg_a, _ := dec.DecodeLong()
			arg_b, _ := dec.DecodeLong()
			ret, err := impl.Add(arg_a, arg_b)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeLong(ret)
			return enc.Bytes(), nil
		case "Echo":
			arg_msg, _ := dec.DecodeString()
			ret, err := impl.Echo(arg_msg)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
