// Code generated by idlc. DO NOT EDIT.
package main

import (
	"encoding/binary"
	"fmt"
	"github.com/sh0jitmy/corba-go/orb/cdr"
	"github.com/sh0jitmy/corba-go/orb/iiop"
)

func Calculator_Math_Skeleton(impl Calculator_Math) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "Add":
			_tmp_arg_a, err := dec.DecodeLong()
			arg_a := int32(_tmp_arg_a)
			_ = err
			_ = dec
			_tmp_arg_b, err := dec.DecodeLong()
			arg_b := int32(_tmp_arg_b)
			_ = err
			_ = dec
			ret, err := impl.Add(arg_a, arg_b)
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeLong(ret)
			return enc.Bytes(), nil
		case "Echo":
			_tmp_arg_msg, err := dec.DecodeString()
			arg_msg := string(_tmp_arg_msg)
			_ = err
			_ = dec
			ret, err := impl.Echo(arg_msg)
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
