// Copyright 2026- The corba-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by idlc. DO NOT EDIT.
package main

import (
	"encoding/binary"
	"fmt"

	"github.com/sh0jitmy/corba-go/orb/cdr"
	"github.com/sh0jitmy/corba-go/orb/iiop"
)

func Calculator_Math_Skeleton(impl Calculator_Math) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "Add":
			_tmp_arg_a, err := dec.DecodeLong()
			arg_a := int32(_tmp_arg_a)
			_ = err
			_ = dec
			_tmp_arg_b, err := dec.DecodeLong()
			arg_b := int32(_tmp_arg_b)
			_ = err
			_ = dec
			ret, err := impl.Add(arg_a, arg_b)
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeLong(ret)
			return enc.Bytes(), nil
		case "Echo":
			_tmp_arg_msg, err := dec.DecodeString()
			arg_msg := string(_tmp_arg_msg)
			_ = err
			_ = dec
			ret, err := impl.Echo(arg_msg)
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
