// Copyright 2026- The corba-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by idlc. DO NOT EDIT.
package naming

import (
	"encoding/binary"
	"fmt"

	"github.com/shjtmy/corba-go/orb/cdr"
	"github.com/shjtmy/corba-go/orb/iiop"
)

type CosNaming_Istring string

type CosNaming_Name []*CosNaming_NameComponent

type CosNaming_BindingList []*CosNaming_Binding

type CosNaming_BindingType uint32

const (
	CosNaming_BindingType_nobject  CosNaming_BindingType = 0
	CosNaming_BindingType_ncontext CosNaming_BindingType = 1
)

type CosNaming_NotFound struct {
	Why          int32
	Rest_of_name CosNaming_Name
}

func (e *CosNaming_NotFound) Error() string {
	return "CosNaming_NotFound"
}

func (s *CosNaming_NotFound) Encode(enc *cdr.Encoder) {
	enc.EncodeLong(s.Why)
	// FIXME: unhandled encode for Name
}

func (s *CosNaming_NotFound) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	_tmp_s_Why, err := dec.DecodeLong()
	s.Why = int32(_tmp_s_Why)
	_ = err
	_ = dec
	if err != nil {
		return err
	}
	// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
	_ = err
	_ = dec
	if err != nil {
		return err
	}
	return nil
}

type CosNaming_CannotProceed struct {
	Cxt          string
	Rest_of_name CosNaming_Name
}

func (e *CosNaming_CannotProceed) Error() string {
	return "CosNaming_CannotProceed"
}

func (s *CosNaming_CannotProceed) Encode(enc *cdr.Encoder) {
	// FIXME: unhandled encode for Object
	// FIXME: unhandled encode for Name
}

func (s *CosNaming_CannotProceed) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	// FIXME: unhandled decode for Object (base: Object)
	_ = err
	_ = dec
	if err != nil {
		return err
	}
	// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
	_ = err
	_ = dec
	if err != nil {
		return err
	}
	return nil
}

type CosNaming_InvalidName struct {
}

func (e *CosNaming_InvalidName) Error() string {
	return "CosNaming_InvalidName"
}

func (s *CosNaming_InvalidName) Encode(enc *cdr.Encoder) {
}

func (s *CosNaming_InvalidName) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosNaming_AlreadyBound struct {
}

func (e *CosNaming_AlreadyBound) Error() string {
	return "CosNaming_AlreadyBound"
}

func (s *CosNaming_AlreadyBound) Encode(enc *cdr.Encoder) {
}

func (s *CosNaming_AlreadyBound) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosNaming_NotEmpty struct {
}

func (e *CosNaming_NotEmpty) Error() string {
	return "CosNaming_NotEmpty"
}

func (s *CosNaming_NotEmpty) Encode(enc *cdr.Encoder) {
}

func (s *CosNaming_NotEmpty) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosNaming_NameComponent struct {
	Id   CosNaming_Istring
	Kind CosNaming_Istring
}

func (s *CosNaming_NameComponent) Encode(enc *cdr.Encoder) {
	enc.EncodeString(string(s.Id))
	enc.EncodeString(string(s.Kind))
}

func (s *CosNaming_NameComponent) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	_tmp_s_Id, err := dec.DecodeString()
	s.Id = CosNaming_Istring(_tmp_s_Id)
	_ = err
	_ = dec
	if err != nil {
		return err
	}
	_tmp_s_Kind, err := dec.DecodeString()
	s.Kind = CosNaming_Istring(_tmp_s_Kind)
	_ = err
	_ = dec
	if err != nil {
		return err
	}
	return nil
}

type CosNaming_Binding struct {
	Binding_name CosNaming_Name
	Binding_type CosNaming_BindingType
}

func (s *CosNaming_Binding) Encode(enc *cdr.Encoder) {
	// FIXME: unhandled encode for Name
	enc.EncodeULong(uint32(s.Binding_type))
}

func (s *CosNaming_Binding) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
	_ = err
	_ = dec
	if err != nil {
		return err
	}
	_tmp_s_Binding_type, err := dec.DecodeULong()
	s.Binding_type = CosNaming_BindingType(_tmp_s_Binding_type)
	_ = err
	_ = dec
	if err != nil {
		return err
	}
	return nil
}

type CosNaming_NamingContext interface {
	Bind(n CosNaming_Name, obj string) error
	Rebind(n CosNaming_Name, obj string) error
	Bind_context(n CosNaming_Name, nc string) error
	Rebind_context(n CosNaming_Name, nc string) error
	Resolve(n CosNaming_Name) (string, error)
	Unbind(n CosNaming_Name) error
	New_context() (string, error)
	Bind_new_context(n CosNaming_Name) (string, error)
	Destroy() error
}

type CosNaming_NamingContext_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCosNaming_NamingContext_Stub(client *iiop.Client, objectKey []byte) CosNaming_NamingContext {
	return &CosNaming_NamingContext_Stub{client: client, objectKey: objectKey}
}

func (s *CosNaming_NamingContext_Stub) Bind(n CosNaming_Name, obj string) error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	// FIXME: unhandled encode for Name
	// FIXME: unhandled encode for Object
	reply, err := s.client.Invoke(s.objectKey, "bind", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) Rebind(n CosNaming_Name, obj string) error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	// FIXME: unhandled encode for Name
	// FIXME: unhandled encode for Object
	reply, err := s.client.Invoke(s.objectKey, "rebind", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) Bind_context(n CosNaming_Name, nc string) error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	// FIXME: unhandled encode for Name
	// FIXME: unhandled encode for Object
	reply, err := s.client.Invoke(s.objectKey, "bind_context", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) Rebind_context(n CosNaming_Name, nc string) error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	// FIXME: unhandled encode for Name
	// FIXME: unhandled encode for Object
	reply, err := s.client.Invoke(s.objectKey, "rebind_context", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) Resolve(n CosNaming_Name) (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	// FIXME: unhandled encode for Name
	reply, err := s.client.Invoke(s.objectKey, "resolve", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	// FIXME: unhandled decode for Object (base: Object)
	var ret string
	_ = err
	_ = dec
	return ret, err
}

func (s *CosNaming_NamingContext_Stub) Unbind(n CosNaming_Name) error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	// FIXME: unhandled encode for Name
	reply, err := s.client.Invoke(s.objectKey, "unbind", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) New_context() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "new_context", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	// FIXME: unhandled decode for Object (base: Object)
	var ret string
	_ = err
	_ = dec
	return ret, err
}

func (s *CosNaming_NamingContext_Stub) Bind_new_context(n CosNaming_Name) (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	// FIXME: unhandled encode for Name
	reply, err := s.client.Invoke(s.objectKey, "bind_new_context", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	// FIXME: unhandled decode for Object (base: Object)
	var ret string
	_ = err
	_ = dec
	return ret, err
}

func (s *CosNaming_NamingContext_Stub) Destroy() error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "destroy", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func CosNaming_NamingContext_Skeleton(impl CosNaming_NamingContext) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "bind":
			// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
			var arg_n CosNaming_Name
			_ = err
			_ = dec
			// FIXME: unhandled decode for Object (base: Object)
			var arg_obj string
			_ = err
			_ = dec
			err = impl.Bind(arg_n, arg_obj)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "rebind":
			// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
			var arg_n CosNaming_Name
			_ = err
			_ = dec
			// FIXME: unhandled decode for Object (base: Object)
			var arg_obj string
			_ = err
			_ = dec
			err = impl.Rebind(arg_n, arg_obj)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "bind_context":
			// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
			var arg_n CosNaming_Name
			_ = err
			_ = dec
			// FIXME: unhandled decode for Object (base: Object)
			var arg_nc string
			_ = err
			_ = dec
			err = impl.Bind_context(arg_n, arg_nc)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "rebind_context":
			// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
			var arg_n CosNaming_Name
			_ = err
			_ = dec
			// FIXME: unhandled decode for Object (base: Object)
			var arg_nc string
			_ = err
			_ = dec
			err = impl.Rebind_context(arg_n, arg_nc)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "resolve":
			// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
			var arg_n CosNaming_Name
			_ = err
			_ = dec
			ret, err := impl.Resolve(arg_n)
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			// FIXME: unhandled encode for Object
			return enc.Bytes(), nil
		case "unbind":
			// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
			var arg_n CosNaming_Name
			_ = err
			_ = dec
			err = impl.Unbind(arg_n)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "new_context":
			ret, err := impl.New_context()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			// FIXME: unhandled encode for Object
			return enc.Bytes(), nil
		case "bind_new_context":
			// FIXME: unhandled decode for Name (base: sequence<NameComponent>)
			var arg_n CosNaming_Name
			_ = err
			_ = dec
			ret, err := impl.Bind_new_context(arg_n)
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			// FIXME: unhandled encode for Object
			return enc.Bytes(), nil
		case "destroy":
			err = impl.Destroy()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
