// Code generated by idlc. DO NOT EDIT.
package naming

import (
	"encoding/binary"
	"fmt"
	"github.com/sh0jitmy/corba-go/orb/cdr"
	"github.com/sh0jitmy/corba-go/orb/iiop"
)

func CosNaming_NamingContext_Skeleton(impl CosNaming_NamingContext) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "bind":
			_len_arg_n, _ := dec.DecodeULong()
			arg_n := make([]*CosNaming_NameComponent, _len_arg_n)
			for _i_arg_n := uint32(0); _i_arg_n < _len_arg_n; _i_arg_n++ {
				arg_n[_i_arg_n] = &CosNaming_NameComponent{}
				err = arg_n[_i_arg_n].Decode(dec)
				_ = err
				_ = dec
			}
			_tmp_arg_obj, err := dec.DecodeString()
			arg_obj := string(_tmp_arg_obj)
			_ = err
			_ = dec
			err = impl.Bind(arg_n, arg_obj)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "rebind":
			_len_arg_n, _ := dec.DecodeULong()
			arg_n := make([]*CosNaming_NameComponent, _len_arg_n)
			for _i_arg_n := uint32(0); _i_arg_n < _len_arg_n; _i_arg_n++ {
				arg_n[_i_arg_n] = &CosNaming_NameComponent{}
				err = arg_n[_i_arg_n].Decode(dec)
				_ = err
				_ = dec
			}
			_tmp_arg_obj, err := dec.DecodeString()
			arg_obj := string(_tmp_arg_obj)
			_ = err
			_ = dec
			err = impl.Rebind(arg_n, arg_obj)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "bind_context":
			_len_arg_n, _ := dec.DecodeULong()
			arg_n := make([]*CosNaming_NameComponent, _len_arg_n)
			for _i_arg_n := uint32(0); _i_arg_n < _len_arg_n; _i_arg_n++ {
				arg_n[_i_arg_n] = &CosNaming_NameComponent{}
				err = arg_n[_i_arg_n].Decode(dec)
				_ = err
				_ = dec
			}
			_tmp_arg_nc, err := dec.DecodeString()
			arg_nc := string(_tmp_arg_nc)
			_ = err
			_ = dec
			err = impl.Bind_context(arg_n, arg_nc)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "rebind_context":
			_len_arg_n, _ := dec.DecodeULong()
			arg_n := make([]*CosNaming_NameComponent, _len_arg_n)
			for _i_arg_n := uint32(0); _i_arg_n < _len_arg_n; _i_arg_n++ {
				arg_n[_i_arg_n] = &CosNaming_NameComponent{}
				err = arg_n[_i_arg_n].Decode(dec)
				_ = err
				_ = dec
			}
			_tmp_arg_nc, err := dec.DecodeString()
			arg_nc := string(_tmp_arg_nc)
			_ = err
			_ = dec
			err = impl.Rebind_context(arg_n, arg_nc)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "resolve":
			_len_arg_n, _ := dec.DecodeULong()
			arg_n := make([]*CosNaming_NameComponent, _len_arg_n)
			for _i_arg_n := uint32(0); _i_arg_n < _len_arg_n; _i_arg_n++ {
				arg_n[_i_arg_n] = &CosNaming_NameComponent{}
				err = arg_n[_i_arg_n].Decode(dec)
				_ = err
				_ = dec
			}
			ret, err := impl.Resolve(arg_n)
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		case "unbind":
			_len_arg_n, _ := dec.DecodeULong()
			arg_n := make([]*CosNaming_NameComponent, _len_arg_n)
			for _i_arg_n := uint32(0); _i_arg_n < _len_arg_n; _i_arg_n++ {
				arg_n[_i_arg_n] = &CosNaming_NameComponent{}
				err = arg_n[_i_arg_n].Decode(dec)
				_ = err
				_ = dec
			}
			err = impl.Unbind(arg_n)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "new_context":
			ret, err := impl.New_context()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		case "bind_new_context":
			_len_arg_n, _ := dec.DecodeULong()
			arg_n := make([]*CosNaming_NameComponent, _len_arg_n)
			for _i_arg_n := uint32(0); _i_arg_n < _len_arg_n; _i_arg_n++ {
				arg_n[_i_arg_n] = &CosNaming_NameComponent{}
				err = arg_n[_i_arg_n].Decode(dec)
				_ = err
				_ = dec
			}
			ret, err := impl.Bind_new_context(arg_n)
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		case "destroy":
			err = impl.Destroy()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
