// Code generated by idlc. DO NOT EDIT.
package naming

import (
	"github.com/sh0jitmy/corba-go/orb/cdr"
)

type CosNaming_Istring string

type CosNaming_Name []*CosNaming_NameComponent

type CosNaming_BindingList []*CosNaming_Binding

type CosNaming_BindingType uint32

const (
	CosNaming_BindingType_nobject CosNaming_BindingType = 0
	CosNaming_BindingType_ncontext CosNaming_BindingType = 1
)

type CosNaming_NotFound struct {
	Why int32
	Rest_of_name CosNaming_Name
}

func (e *CosNaming_NotFound) Error() string {
	return "CosNaming_NotFound"
}

func (s *CosNaming_NotFound) Encode(enc *cdr.Encoder) {
	enc.EncodeLong(s.Why)
	enc.EncodeULong(uint32(len(s.Rest_of_name)))
	for _, v := range s.Rest_of_name {
		v.Encode(enc)
	}
}

func (s *CosNaming_NotFound) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	_tmp_s_Why, err := dec.DecodeLong()
	s.Why = int32(_tmp_s_Why)
	_ = err
	_ = dec
	if err != nil { return err }
	_len_s_Rest_of_name, _ := dec.DecodeULong()
	s.Rest_of_name = make([]*CosNaming_NameComponent, _len_s_Rest_of_name)
	for _i_s_Rest_of_name := uint32(0); _i_s_Rest_of_name < _len_s_Rest_of_name; _i_s_Rest_of_name++ {
		s.Rest_of_name[_i_s_Rest_of_name] = &CosNaming_NameComponent{}
		err = s.Rest_of_name[_i_s_Rest_of_name].Decode(dec)
		_ = err
		_ = dec
	}
	if err != nil { return err }
	return nil
}

type CosNaming_CannotProceed struct {
	Cxt string
	Rest_of_name CosNaming_Name
}

func (e *CosNaming_CannotProceed) Error() string {
	return "CosNaming_CannotProceed"
}

func (s *CosNaming_CannotProceed) Encode(enc *cdr.Encoder) {
	enc.EncodeString(s.Cxt)
	enc.EncodeULong(uint32(len(s.Rest_of_name)))
	for _, v := range s.Rest_of_name {
		v.Encode(enc)
	}
}

func (s *CosNaming_CannotProceed) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	_tmp_s_Cxt, err := dec.DecodeString()
	s.Cxt = string(_tmp_s_Cxt)
	_ = err
	_ = dec
	if err != nil { return err }
	_len_s_Rest_of_name, _ := dec.DecodeULong()
	s.Rest_of_name = make([]*CosNaming_NameComponent, _len_s_Rest_of_name)
	for _i_s_Rest_of_name := uint32(0); _i_s_Rest_of_name < _len_s_Rest_of_name; _i_s_Rest_of_name++ {
		s.Rest_of_name[_i_s_Rest_of_name] = &CosNaming_NameComponent{}
		err = s.Rest_of_name[_i_s_Rest_of_name].Decode(dec)
		_ = err
		_ = dec
	}
	if err != nil { return err }
	return nil
}

type CosNaming_InvalidName struct {
}

func (e *CosNaming_InvalidName) Error() string {
	return "CosNaming_InvalidName"
}

func (s *CosNaming_InvalidName) Encode(enc *cdr.Encoder) {
}

func (s *CosNaming_InvalidName) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosNaming_AlreadyBound struct {
}

func (e *CosNaming_AlreadyBound) Error() string {
	return "CosNaming_AlreadyBound"
}

func (s *CosNaming_AlreadyBound) Encode(enc *cdr.Encoder) {
}

func (s *CosNaming_AlreadyBound) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosNaming_NotEmpty struct {
}

func (e *CosNaming_NotEmpty) Error() string {
	return "CosNaming_NotEmpty"
}

func (s *CosNaming_NotEmpty) Encode(enc *cdr.Encoder) {
}

func (s *CosNaming_NotEmpty) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosNaming_NameComponent struct {
	Id CosNaming_Istring
	Kind CosNaming_Istring
}

func (s *CosNaming_NameComponent) Encode(enc *cdr.Encoder) {
	enc.EncodeString(string(s.Id))
	enc.EncodeString(string(s.Kind))
}

func (s *CosNaming_NameComponent) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	_tmp_s_Id, err := dec.DecodeString()
	s.Id = CosNaming_Istring(_tmp_s_Id)
	_ = err
	_ = dec
	if err != nil { return err }
	_tmp_s_Kind, err := dec.DecodeString()
	s.Kind = CosNaming_Istring(_tmp_s_Kind)
	_ = err
	_ = dec
	if err != nil { return err }
	return nil
}

type CosNaming_Binding struct {
	Binding_name CosNaming_Name
	Binding_type CosNaming_BindingType
}

func (s *CosNaming_Binding) Encode(enc *cdr.Encoder) {
	enc.EncodeULong(uint32(len(s.Binding_name)))
	for _, v := range s.Binding_name {
		v.Encode(enc)
	}
	enc.EncodeULong(uint32(s.Binding_type))
}

func (s *CosNaming_Binding) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	_len_s_Binding_name, _ := dec.DecodeULong()
	s.Binding_name = make([]*CosNaming_NameComponent, _len_s_Binding_name)
	for _i_s_Binding_name := uint32(0); _i_s_Binding_name < _len_s_Binding_name; _i_s_Binding_name++ {
		s.Binding_name[_i_s_Binding_name] = &CosNaming_NameComponent{}
		err = s.Binding_name[_i_s_Binding_name].Decode(dec)
		_ = err
		_ = dec
	}
	if err != nil { return err }
	_tmp_s_Binding_type, err := dec.DecodeULong()
	s.Binding_type = CosNaming_BindingType(_tmp_s_Binding_type)
	_ = err
	_ = dec
	if err != nil { return err }
	return nil
}

type CosNaming_NamingContext interface {
	Bind(n CosNaming_Name, obj string) (error)
	Rebind(n CosNaming_Name, obj string) (error)
	Bind_context(n CosNaming_Name, nc string) (error)
	Rebind_context(n CosNaming_Name, nc string) (error)
	Resolve(n CosNaming_Name) (string, error)
	Unbind(n CosNaming_Name) (error)
	New_context() (string, error)
	Bind_new_context(n CosNaming_Name) (string, error)
	Destroy() (error)
}

