// Code generated by idlc. DO NOT EDIT.
package naming

import (
	"encoding/binary"
	"github.com/sh0jitmy/corba-go/orb/cdr"
	"github.com/sh0jitmy/corba-go/orb/iiop"
)

type CosNaming_NamingContext_Stub struct {
	client *iiop.Client
	objectKey []byte
}

func NewCosNaming_NamingContext_Stub(client *iiop.Client, objectKey []byte) CosNaming_NamingContext {
	return &CosNaming_NamingContext_Stub{client: client, objectKey: objectKey}
}

func (s *CosNaming_NamingContext_Stub) Bind(n CosNaming_Name, obj string) (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeULong(uint32(len(n)))
	for _, v := range n {
		v.Encode(enc)
	}
	enc.EncodeString(obj)
	reply, err := s.client.Invoke(s.objectKey, "bind", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) Rebind(n CosNaming_Name, obj string) (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeULong(uint32(len(n)))
	for _, v := range n {
		v.Encode(enc)
	}
	enc.EncodeString(obj)
	reply, err := s.client.Invoke(s.objectKey, "rebind", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) Bind_context(n CosNaming_Name, nc string) (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeULong(uint32(len(n)))
	for _, v := range n {
		v.Encode(enc)
	}
	enc.EncodeString(nc)
	reply, err := s.client.Invoke(s.objectKey, "bind_context", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) Rebind_context(n CosNaming_Name, nc string) (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeULong(uint32(len(n)))
	for _, v := range n {
		v.Encode(enc)
	}
	enc.EncodeString(nc)
	reply, err := s.client.Invoke(s.objectKey, "rebind_context", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) Resolve(n CosNaming_Name) (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeULong(uint32(len(n)))
	for _, v := range n {
		v.Encode(enc)
	}
	reply, err := s.client.Invoke(s.objectKey, "resolve", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeString()
	ret := string(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

func (s *CosNaming_NamingContext_Stub) Unbind(n CosNaming_Name) (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeULong(uint32(len(n)))
	for _, v := range n {
		v.Encode(enc)
	}
	reply, err := s.client.Invoke(s.objectKey, "unbind", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosNaming_NamingContext_Stub) New_context() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "new_context", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeString()
	ret := string(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

func (s *CosNaming_NamingContext_Stub) Bind_new_context(n CosNaming_Name) (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeULong(uint32(len(n)))
	for _, v := range n {
		v.Encode(enc)
	}
	reply, err := s.client.Invoke(s.objectKey, "bind_new_context", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeString()
	ret := string(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

func (s *CosNaming_NamingContext_Stub) Destroy() (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "destroy", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

