// Copyright 2026- The corba-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by idlc. DO NOT EDIT.
package event

import (
	"encoding/binary"
	"fmt"

	"github.com/shjtmy/corba-go/orb/cdr"
	"github.com/shjtmy/corba-go/orb/iiop"
)

type CosEvent_Disconnected struct {
}

func (e *CosEvent_Disconnected) Error() string {
	return "CosEvent_Disconnected"
}

func (s *CosEvent_Disconnected) Encode(enc *cdr.Encoder) {
}

func (s *CosEvent_Disconnected) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosEvent_AlreadyConnected struct {
}

func (e *CosEvent_AlreadyConnected) Error() string {
	return "CosEvent_AlreadyConnected"
}

func (s *CosEvent_AlreadyConnected) Encode(enc *cdr.Encoder) {
}

func (s *CosEvent_AlreadyConnected) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosEvent_TypeError struct {
}

func (e *CosEvent_TypeError) Error() string {
	return "CosEvent_TypeError"
}

func (s *CosEvent_TypeError) Encode(enc *cdr.Encoder) {
}

func (s *CosEvent_TypeError) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosEvent_PushConsumer interface {
	Push(data cdr.Any) error
	Disconnect_push_consumer() error
}

type CosEvent_PushConsumer_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCosEvent_PushConsumer_Stub(client *iiop.Client, objectKey []byte) CosEvent_PushConsumer {
	return &CosEvent_PushConsumer_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_PushConsumer_Stub) Push(data cdr.Any) error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeAny(data)
	reply, err := s.client.Invoke(s.objectKey, "push", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosEvent_PushConsumer_Stub) Disconnect_push_consumer() error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "disconnect_push_consumer", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func CosEvent_PushConsumer_Skeleton(impl CosEvent_PushConsumer) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "push":
			arg_data, err := dec.DecodeAny()
			_ = err
			_ = dec
			err = impl.Push(arg_data)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "disconnect_push_consumer":
			err = impl.Disconnect_push_consumer()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}

type CosEvent_PushSupplier interface {
	Disconnect_push_supplier() error
}

type CosEvent_PushSupplier_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCosEvent_PushSupplier_Stub(client *iiop.Client, objectKey []byte) CosEvent_PushSupplier {
	return &CosEvent_PushSupplier_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_PushSupplier_Stub) Disconnect_push_supplier() error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "disconnect_push_supplier", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func CosEvent_PushSupplier_Skeleton(impl CosEvent_PushSupplier) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "disconnect_push_supplier":
			err = impl.Disconnect_push_supplier()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}

type CosEvent_ProxyPushConsumer interface {
	Connect_push_supplier(push_supplier string) error
	Push(data cdr.Any) error
	Disconnect_push_consumer() error
}

type CosEvent_ProxyPushConsumer_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCosEvent_ProxyPushConsumer_Stub(client *iiop.Client, objectKey []byte) CosEvent_ProxyPushConsumer {
	return &CosEvent_ProxyPushConsumer_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_ProxyPushConsumer_Stub) Connect_push_supplier(push_supplier string) error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	// FIXME: unhandled encode for Object
	reply, err := s.client.Invoke(s.objectKey, "connect_push_supplier", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosEvent_ProxyPushConsumer_Stub) Push(data cdr.Any) error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeAny(data)
	reply, err := s.client.Invoke(s.objectKey, "push", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosEvent_ProxyPushConsumer_Stub) Disconnect_push_consumer() error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "disconnect_push_consumer", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func CosEvent_ProxyPushConsumer_Skeleton(impl CosEvent_ProxyPushConsumer) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "connect_push_supplier":
			// FIXME: unhandled decode for Object (base: Object)
			var arg_push_supplier string
			_ = err
			_ = dec
			err = impl.Connect_push_supplier(arg_push_supplier)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "push":
			arg_data, err := dec.DecodeAny()
			_ = err
			_ = dec
			err = impl.Push(arg_data)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "disconnect_push_consumer":
			err = impl.Disconnect_push_consumer()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}

type CosEvent_ProxyPushSupplier interface {
	Connect_push_consumer(push_consumer string) error
	Disconnect_push_supplier() error
}

type CosEvent_ProxyPushSupplier_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCosEvent_ProxyPushSupplier_Stub(client *iiop.Client, objectKey []byte) CosEvent_ProxyPushSupplier {
	return &CosEvent_ProxyPushSupplier_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_ProxyPushSupplier_Stub) Connect_push_consumer(push_consumer string) error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	// FIXME: unhandled encode for Object
	reply, err := s.client.Invoke(s.objectKey, "connect_push_consumer", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosEvent_ProxyPushSupplier_Stub) Disconnect_push_supplier() error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "disconnect_push_supplier", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func CosEvent_ProxyPushSupplier_Skeleton(impl CosEvent_ProxyPushSupplier) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "connect_push_consumer":
			// FIXME: unhandled decode for Object (base: Object)
			var arg_push_consumer string
			_ = err
			_ = dec
			err = impl.Connect_push_consumer(arg_push_consumer)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "disconnect_push_supplier":
			err = impl.Disconnect_push_supplier()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}

type CosEvent_ConsumerAdmin interface {
	Obtain_push_supplier() (string, error)
}

type CosEvent_ConsumerAdmin_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCosEvent_ConsumerAdmin_Stub(client *iiop.Client, objectKey []byte) CosEvent_ConsumerAdmin {
	return &CosEvent_ConsumerAdmin_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_ConsumerAdmin_Stub) Obtain_push_supplier() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "obtain_push_supplier", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	// FIXME: unhandled decode for Object (base: Object)
	var ret string
	_ = err
	_ = dec
	return ret, err
}

func CosEvent_ConsumerAdmin_Skeleton(impl CosEvent_ConsumerAdmin) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "obtain_push_supplier":
			ret, err := impl.Obtain_push_supplier()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			// FIXME: unhandled encode for Object
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}

type CosEvent_SupplierAdmin interface {
	Obtain_push_consumer() (string, error)
}

type CosEvent_SupplierAdmin_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCosEvent_SupplierAdmin_Stub(client *iiop.Client, objectKey []byte) CosEvent_SupplierAdmin {
	return &CosEvent_SupplierAdmin_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_SupplierAdmin_Stub) Obtain_push_consumer() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "obtain_push_consumer", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	// FIXME: unhandled decode for Object (base: Object)
	var ret string
	_ = err
	_ = dec
	return ret, err
}

func CosEvent_SupplierAdmin_Skeleton(impl CosEvent_SupplierAdmin) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "obtain_push_consumer":
			ret, err := impl.Obtain_push_consumer()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			// FIXME: unhandled encode for Object
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}

type CosEvent_EventChannel interface {
	For_consumers() (string, error)
	For_suppliers() (string, error)
	Destroy() error
}

type CosEvent_EventChannel_Stub struct {
	client    *iiop.Client
	objectKey []byte
}

func NewCosEvent_EventChannel_Stub(client *iiop.Client, objectKey []byte) CosEvent_EventChannel {
	return &CosEvent_EventChannel_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_EventChannel_Stub) For_consumers() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "for_consumers", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	// FIXME: unhandled decode for Object (base: Object)
	var ret string
	_ = err
	_ = dec
	return ret, err
}

func (s *CosEvent_EventChannel_Stub) For_suppliers() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "for_suppliers", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	// FIXME: unhandled decode for Object (base: Object)
	var ret string
	_ = err
	_ = dec
	return ret, err
}

func (s *CosEvent_EventChannel_Stub) Destroy() error {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "destroy", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func CosEvent_EventChannel_Skeleton(impl CosEvent_EventChannel) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "for_consumers":
			ret, err := impl.For_consumers()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			// FIXME: unhandled encode for Object
			return enc.Bytes(), nil
		case "for_suppliers":
			ret, err := impl.For_suppliers()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			// FIXME: unhandled encode for Object
			return enc.Bytes(), nil
		case "destroy":
			err = impl.Destroy()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
