// Code generated by idlc. DO NOT EDIT.
package event

import (
	"encoding/binary"
	"github.com/sh0jitmy/corba-go/orb/cdr"
	"github.com/sh0jitmy/corba-go/orb/iiop"
)

type CosEvent_PushConsumer_Stub struct {
	client *iiop.Client
	objectKey []byte
}

func NewCosEvent_PushConsumer_Stub(client *iiop.Client, objectKey []byte) CosEvent_PushConsumer {
	return &CosEvent_PushConsumer_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_PushConsumer_Stub) Push(data cdr.Any) (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeAny(data)
	reply, err := s.client.Invoke(s.objectKey, "push", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosEvent_PushConsumer_Stub) Disconnect_push_consumer() (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "disconnect_push_consumer", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

type CosEvent_PushSupplier_Stub struct {
	client *iiop.Client
	objectKey []byte
}

func NewCosEvent_PushSupplier_Stub(client *iiop.Client, objectKey []byte) CosEvent_PushSupplier {
	return &CosEvent_PushSupplier_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_PushSupplier_Stub) Disconnect_push_supplier() (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "disconnect_push_supplier", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

type CosEvent_ProxyPushConsumer_Stub struct {
	client *iiop.Client
	objectKey []byte
}

func NewCosEvent_ProxyPushConsumer_Stub(client *iiop.Client, objectKey []byte) CosEvent_ProxyPushConsumer {
	return &CosEvent_ProxyPushConsumer_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_ProxyPushConsumer_Stub) Connect_push_supplier(push_supplier string) (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeString(push_supplier)
	reply, err := s.client.Invoke(s.objectKey, "connect_push_supplier", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosEvent_ProxyPushConsumer_Stub) Push(data cdr.Any) (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeAny(data)
	reply, err := s.client.Invoke(s.objectKey, "push", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosEvent_ProxyPushConsumer_Stub) Disconnect_push_consumer() (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "disconnect_push_consumer", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

type CosEvent_ProxyPushSupplier_Stub struct {
	client *iiop.Client
	objectKey []byte
}

func NewCosEvent_ProxyPushSupplier_Stub(client *iiop.Client, objectKey []byte) CosEvent_ProxyPushSupplier {
	return &CosEvent_ProxyPushSupplier_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_ProxyPushSupplier_Stub) Connect_push_consumer(push_consumer string) (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	enc.EncodeString(push_consumer)
	reply, err := s.client.Invoke(s.objectKey, "connect_push_consumer", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

func (s *CosEvent_ProxyPushSupplier_Stub) Disconnect_push_supplier() (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "disconnect_push_supplier", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

type CosEvent_ConsumerAdmin_Stub struct {
	client *iiop.Client
	objectKey []byte
}

func NewCosEvent_ConsumerAdmin_Stub(client *iiop.Client, objectKey []byte) CosEvent_ConsumerAdmin {
	return &CosEvent_ConsumerAdmin_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_ConsumerAdmin_Stub) Obtain_push_supplier() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "obtain_push_supplier", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeString()
	ret := string(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

type CosEvent_SupplierAdmin_Stub struct {
	client *iiop.Client
	objectKey []byte
}

func NewCosEvent_SupplierAdmin_Stub(client *iiop.Client, objectKey []byte) CosEvent_SupplierAdmin {
	return &CosEvent_SupplierAdmin_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_SupplierAdmin_Stub) Obtain_push_consumer() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "obtain_push_consumer", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeString()
	ret := string(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

type CosEvent_EventChannel_Stub struct {
	client *iiop.Client
	objectKey []byte
}

func NewCosEvent_EventChannel_Stub(client *iiop.Client, objectKey []byte) CosEvent_EventChannel {
	return &CosEvent_EventChannel_Stub{client: client, objectKey: objectKey}
}

func (s *CosEvent_EventChannel_Stub) For_consumers() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "for_consumers", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeString()
	ret := string(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

func (s *CosEvent_EventChannel_Stub) For_suppliers() (string, error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "for_suppliers", enc.Bytes())
	if err != nil {
		var zero string
		return zero, err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	_tmp_ret, err := dec.DecodeString()
	ret := string(_tmp_ret)
	_ = err
	_ = dec
	return ret, err
}

func (s *CosEvent_EventChannel_Stub) Destroy() (error) {
	enc := cdr.NewEncoder(binary.LittleEndian)
	reply, err := s.client.Invoke(s.objectKey, "destroy", enc.Bytes())
	if err != nil {
		return err
	}

	dec := cdr.NewDecoder(reply, binary.LittleEndian)
	_ = dec
	return nil
}

