// Copyright 2026- The corba-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by idlc. DO NOT EDIT.
package event

import (
	"github.com/sh0jitmy/corba-go/orb/cdr"
)

type CosEvent_Disconnected struct {
}

func (e *CosEvent_Disconnected) Error() string {
	return "CosEvent_Disconnected"
}

func (s *CosEvent_Disconnected) Encode(enc *cdr.Encoder) {
}

func (s *CosEvent_Disconnected) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosEvent_AlreadyConnected struct {
}

func (e *CosEvent_AlreadyConnected) Error() string {
	return "CosEvent_AlreadyConnected"
}

func (s *CosEvent_AlreadyConnected) Encode(enc *cdr.Encoder) {
}

func (s *CosEvent_AlreadyConnected) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosEvent_TypeError struct {
}

func (e *CosEvent_TypeError) Error() string {
	return "CosEvent_TypeError"
}

func (s *CosEvent_TypeError) Encode(enc *cdr.Encoder) {
}

func (s *CosEvent_TypeError) Decode(dec *cdr.Decoder) error {
	var err error
	_ = err
	_ = dec
	return nil
}

type CosEvent_PushConsumer interface {
	Push(data cdr.Any) error
	Disconnect_push_consumer() error
}

type CosEvent_PushSupplier interface {
	Disconnect_push_supplier() error
}

type CosEvent_ProxyPushConsumer interface {
	Connect_push_supplier(push_supplier string) error
	Push(data cdr.Any) error
	Disconnect_push_consumer() error
}

type CosEvent_ProxyPushSupplier interface {
	Connect_push_consumer(push_consumer string) error
	Disconnect_push_supplier() error
}

type CosEvent_ConsumerAdmin interface {
	Obtain_push_supplier() (string, error)
}

type CosEvent_SupplierAdmin interface {
	Obtain_push_consumer() (string, error)
}

type CosEvent_EventChannel interface {
	For_consumers() (string, error)
	For_suppliers() (string, error)
	Destroy() error
}
