// Copyright 2026- The corba-go Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by idlc. DO NOT EDIT.
package event

import (
	"encoding/binary"
	"fmt"

	"github.com/sh0jitmy/corba-go/orb/cdr"
	"github.com/sh0jitmy/corba-go/orb/iiop"
)

func CosEvent_PushConsumer_Skeleton(impl CosEvent_PushConsumer) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "push":
			arg_data, err := dec.DecodeAny()
			_ = err
			_ = dec
			err = impl.Push(arg_data)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "disconnect_push_consumer":
			err = impl.Disconnect_push_consumer()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
func CosEvent_PushSupplier_Skeleton(impl CosEvent_PushSupplier) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "disconnect_push_supplier":
			err = impl.Disconnect_push_supplier()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
func CosEvent_ProxyPushConsumer_Skeleton(impl CosEvent_ProxyPushConsumer) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "connect_push_supplier":
			_tmp_arg_push_supplier, err := dec.DecodeString()
			arg_push_supplier := string(_tmp_arg_push_supplier)
			_ = err
			_ = dec
			err = impl.Connect_push_supplier(arg_push_supplier)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "push":
			arg_data, err := dec.DecodeAny()
			_ = err
			_ = dec
			err = impl.Push(arg_data)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "disconnect_push_consumer":
			err = impl.Disconnect_push_consumer()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
func CosEvent_ProxyPushSupplier_Skeleton(impl CosEvent_ProxyPushSupplier) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "connect_push_consumer":
			_tmp_arg_push_consumer, err := dec.DecodeString()
			arg_push_consumer := string(_tmp_arg_push_consumer)
			_ = err
			_ = dec
			err = impl.Connect_push_consumer(arg_push_consumer)
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		case "disconnect_push_supplier":
			err = impl.Disconnect_push_supplier()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
func CosEvent_ConsumerAdmin_Skeleton(impl CosEvent_ConsumerAdmin) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "obtain_push_supplier":
			ret, err := impl.Obtain_push_supplier()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
func CosEvent_SupplierAdmin_Skeleton(impl CosEvent_SupplierAdmin) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "obtain_push_consumer":
			ret, err := impl.Obtain_push_consumer()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
func CosEvent_EventChannel_Skeleton(impl CosEvent_EventChannel) iiop.Handler {
	return func(objectKey []byte, operation string, reqPayload []byte) ([]byte, error) {
		dec := cdr.NewDecoder(reqPayload, binary.LittleEndian)
		var err error
		_ = err
		_ = dec
		switch operation {
		case "for_consumers":
			ret, err := impl.For_consumers()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		case "for_suppliers":
			ret, err := impl.For_suppliers()
			_ = ret
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			enc.EncodeString(ret)
			return enc.Bytes(), nil
		case "destroy":
			err = impl.Destroy()
			if err != nil {
				return nil, err
			}
			enc := cdr.NewEncoder(binary.LittleEndian)
			return enc.Bytes(), nil
		default:
			return nil, fmt.Errorf("Unknown operation: %s", operation)
		}
	}
}
